version: 2.1
commands:
  cached-bundle:
    steps:
      - restore_cache:
        keys:
          - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1-{{ arch }}-{{ .Branch }}
          - gem-cache-v1
      - run: bundle install --path vendor/bundle
      - save_cache:
        key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
  rspec-tests:
    steps:
      - run: |
        bundle exec rspec \
      --profile 10 \
      --format progress \
      ${circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)}

executors:
  ruby-2-6-2:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
jobs:
  build:
    working_directory: ~/app
    executor: ruby-2-6-2
    steps:
      - checkout
      - cached-bundle
      - rspec-tests

workflows:
  main:
    jobs:
      - build
